backend:
  name: github
  repo: TheWizardOfOS3CG/The_Wizard_Of_Os-Cyber_Girl
  branch: main
  base_url: https://github.com
  auth_endpoint: login/oauth/authorize
  client_id: "Ov23liKjQlGm4rhgFA1E"

media_folder: "uploads"
public_folder: "/uploads"

# Configurazione del CMS
site_url: "https://thewizardofos3cg.github.io/The_Wizard_Of_Os-Cyber_Girl"
display_url: "https://thewizardofos3cg.github.io/The_Wizard_Of_Os-Cyber_Girl"
logo_url: "https://thewizardofos3cg.github.io/The_Wizard_Of_Os-Cyber_Girl/logo.jpg"

# Impostazioni di autenticazione
publish_mode: editorial_workflow
slug:
  encoding: "ascii"
  clean_accents: true

# Raccolte di contenuti gestiti dal CMS
collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
