backend:
  name: github
  repo: TheWizardOfOS/wizard-cms
  branch: main
  auth_scope: repo

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pagine"
    files:
      - label: "Homepage"
        name: "index"
        file: "index.html"
        fields:
          - { label: "Titolo", name: "title", widget: "string" }
          - { label: "Contenuto", name: "body", widget: "markdown" }

  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Contenuto", name: "body", widget: "markdown" }
