backend:
  name: git-gateway
  branch: main  # Assicurati che sia il branch corretto

media_folder: "images/uploads" # Cartella per caricare immagini
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pagine"
    files:
      - label: "Homepage"
        name: "index"
        file: "index.html"
        fields:
          - { label: "Titolo", name: "title", widget: "string" }
          - { label: "Contenuto", name: "body", widget: "markdown" }

      - label: "Chi Sono"
        name: "chi_sono"
        file: "chi_sono.html"
        fields:
          - { label: "Titolo", name: "title", widget: "string" }
          - { label: "Contenuto", name: "body", widget: "markdown" }

      - label: "Servizi"
        name: "servizi"
        file: "servizi.html"
        fields:
          - { label: "Titolo", name: "title", widget: "string" }
          - { label: "Contenuto", name: "body", widget: "markdown" }

      - label: "Blog"
        name: "blog"
        file: "blog.html"
        fields:
          - { label: "Titolo", name: "title", widget: "string" }
          - { label: "Contenuto", name: "body", widget: "markdown" }

      - label: "Contatti"
        name: "contatti"
        file: "contatti.html"
        fields:
          - { label: "Titolo", name: "title", widget: "string" }
          - { label: "Contenuto", name: "body", widget: "markdown" }
