backend:
  name: github
  repo: TheWizardOfOS3CG/The_Wizard_Of_Os-Cyber_Girl  # Nome del repository corretto
  branch: main
  auth_endpoint: auth
  base_url: https://github.com
  site_domain: thewizardofosandcybergirl.netlify.app
  app_id: Ov23liKjQlGm4rhgFA1E  # Il tuo Client ID OAuth
  redirect_uri: "https://thewizardofosandcybergirl.netlify.app/admin/"

media_folder: "uploads"
public_folder: "/uploads"

# Configurazione del CMS
site_url: "https://thewizardofos3cg.github.io/The_Wizard_Of_Os-Cyber_Girl"
display_url: "https://thewizardofos3cg.github.io/The_Wizard_Of_Os-Cyber_Girl"
logo_url: "https://thewizardofos3cg.github.io/The_Wizard_Of_Os-Cyber_Girl/logo.jpg"

# Impostazioni di autenticazione
publish_mode: editorial_workflow
slug:
  encoding: "ascii"
  clean_accents: true

# Raccolte di contenuti gestiti dal CMS
collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
