backend:
  name: github
  repo: TheWizardOfOS/thewizardofos-cms
  branch: main
  site_domain: thewizardofosandcybergirl.netlify.app
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Contenuto", name: "body", widget: "markdown" }
